version: '3.7'
networks:
  study-predictor-network:
    driver: bridge
services:
  study-predictor:
    build: code
    image: study-predictor
    ports:
      - "8008:80"
    networks:
      - study-predictor-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--debug", "--port", "80", "--reload-dir", "/app"]
    volumes:
      - ./code/app:/app
  nginx: 
    image: nginx:1.19.0-alpine
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/conf.d/default.conf 
#      - ./nginx/error.log:/etc/nginx/error_log.log
#      - ./nginx/cache/:/etc/nginx/cache
#      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 8090:8080
      - 444:443
    depends_on:
      - study-predictor
    networks:
      - study-predictor-network
    
